In [ ]:
• Create a new MLP with any given number of inputs, any number of
outputs (can be sigmoidal or linear), and any number of hidden
units (sigmoidal/tanh) in a single layer.
• Initialise the weights of the MLP to small random values
• Predict the outputs corresponding to an input vector
• Implement learning by backpropagation


In [1]:
import numpy as np

class MLP:
    def __init__(self, ni, nh, no):
        self.no_of_inputs = ni
        self.no_of_hidden_units = nh
        self.no_of_outputs = no
        self.w1 = []
        self.w2 = []
        self.dw1 = []
        self.dw2 = []
        self.z1 = []
        self.z2 = []
        self.h = []
        self.o = []

    def Sigmoid(self, sig_input, der=False):
        if der:
            return np.exp(-sig_input) / (1 + np.exp(-sig_input)) ** 2
        else:
            return 1 / (1 + np.exp(-sig_input))

    def Tanh(self, tanh_input, der=False):
        if der:
            return 1 - (np.power(self.Tanh(tanh_input), 2))
        else:
            return (2 / (1 + np.exp(tanh_input * -2))) - 1

    def randomise(self):
        self.w1 = np.array((np.random.uniform(0.0, 1, (self.no_of_inputs,self.no_of_hidden_units))).tolist())
        self.dw1 = np.dot(self.w1, 0)
        self.w2 = np.array((np.random.uniform(0.0, 1, (self.no_of_hidden_units, self.no_of_outputs))).tolist())
        self.dw2 = np.dot(self.w2, 0)

    def forward(self, input_vectors, tan=False):
        self.z1 = np.dot(input_vectors, self.w1)
        if tan:
            self.h = self.Tanh(self.z1)
        else:
            self.h = self.Sigmoid(self.z1)

        self.z2 = np.dot(self.h, self.w2)
        if tan:
            self.o = self.Tanh(self.z2)
        else:
            self.o = self.Sigmoid(self.z2)

    def backwards(self, input_vectors, target, tan=False):
        output_error = np.subtract(target, self.o)
        if tan:
            activation_out_2 = self.Tanh(self.z2, True)
            activation_out_1 = self.Tanh(self.z1, True)
        else:
            activation_out_2 = self.Sigmoid(self.z2, True)
            activation_out_1 = self.Sigmoid(self.z1, True)

        dw2_a = np.multiply(output_error, activation_out_2)
        self.dw2 = np.dot(self.h.T, dw2_a)
        dw1_a = np.multiply(np.dot(dw2_a, self.w2.T), activation_out_1)
        self.dw1 = np.dot(input_vectors.T, dw1_a)
        return np.mean(np.abs(output_error))

    def updateWeights(self, learning_rate):
        self.w1 = self.w1 + (learning_rate * self.dw1)
        self.w2 = self.w2 + (learning_rate * self.dw2)
        self.dw1 = 0
        self.dw2 = 0

In [2]:
np.random.seed(1)

In [3]:
xorI = np.array([[0, 0], 
                 [0, 1], 
                 [1, 0], 
                 [1, 1]])
xorO = np.array([[0], 
                 [1], 
                 [1], 
                 [0]])

no_of_epochs = 10000
learning_rate = 0.5
inputs = 2
hidden = 4
outputs = 1
mlp = MLP(inputs, hidden, outputs)
mlp.randomise()

print('Pre-Training Testing: ')
for i in range(len(xorI)):
    mlp.forward(xorI[i])
    print('Desired Output: ' + str(xorO[i]))
    print('Predicted Output: ' + str(mlp.o))

print()
print('After Training: ')
for i in range(0, no_of_epochs):
    error = 0
    mlp.forward(xorI)
    error = mlp.backwards(xorI, xorO)
    mlp.updateWeights(learning_rate)
    if (i + 1) % (no_of_epochs/10) == 0:
        length = len(str(i))
        while length < 10:
            length += 1
        print('Epoch: ' + str(i + 1) + "  " + ' Error: ' + str(error))

print()
print('Testing:')
for i in range(len(xorI)):
    mlp.forward(xorI[i])
    print('Desired Output: ' + str(xorO[i]))
    print('Predicted Output: ' + str(mlp.o))

Pre-Training Testing: 
Desired Output: [0]
Predicted Output: [0.73497243]
Desired Output: [1]
Predicted Output: [0.75492189]
Desired Output: [1]
Predicted Output: [0.76945373]
Desired Output: [0]
Predicted Output: [0.78668195]

After Training: 
Epoch: 1000   Error: 0.49840015458399994
Epoch: 2000   Error: 0.1545451073718641
Epoch: 3000   Error: 0.07557727369432107
Epoch: 4000   Error: 0.055876231630467364
Epoch: 5000   Error: 0.04602011276370544
Epoch: 6000   Error: 0.039835911785095546
Epoch: 7000   Error: 0.03548186646788337
Epoch: 8000   Error: 0.03219253229516872
Epoch: 9000   Error: 0.029585839662957157
Epoch: 10000   Error: 0.027447505278416783

Testing:
Desired Output: [0]
Predicted Output: [0.03028019]
Desired Output: [1]
Predicted Output: [0.97206353]
Desired Output: [1]
Predicted Output: [0.97375232]
Desired Output: [0]
Predicted Output: [0.02531787]


In [4]:
xorI = np.array([[0, 0], 
                 [0, 1], 
                 [1, 0], 
                 [1, 1]])
xorO = np.array([[0], 
                 [1], 
                 [1], 
                 [0]])

no_of_epochs = 100000
learning_rate = 0.8
inputs = 2
hidden = 4
outputs = 1
mlp = MLP(inputs, hidden, outputs)
mlp.randomise()

print('Pre-Training Testing: ')
for i in range(len(xorI)):
    mlp.forward(xorI[i])
    print('Desired Output: ' + str(xorO[i]))
    print('Predicted Output: ' + str(mlp.o))

print()
print('After Training: ')
for i in range(0, no_of_epochs):
    error = 0
    mlp.forward(xorI)
    error = mlp.backwards(xorI, xorO)
    mlp.updateWeights(learning_rate)
    if (i + 1) % (no_of_epochs/10) == 0:
        length = len(str(i))
        while length < 10:
            length += 1
        print('Epoch: ' + str(i + 1) + "  " + ' Error: ' + str(error))

print()
print('Testing:')
for i in range(len(xorI)):
    mlp.forward(xorI[i])
    print('Desired Output: ' + str(xorO[i]))
    print('Predicted Output: ' + str(mlp.o))

Pre-Training Testing: 
Desired Output: [0]
Predicted Output: [0.80017308]
Desired Output: [1]
Predicted Output: [0.83844586]
Desired Output: [1]
Predicted Output: [0.85095028]
Desired Output: [0]
Predicted Output: [0.87662252]

After Training: 
Epoch: 10000   Error: 0.020732000813817028
Epoch: 20000   Error: 0.01429237287801423
Epoch: 30000   Error: 0.011550069258578682
Epoch: 40000   Error: 0.009942939190735045
Epoch: 50000   Error: 0.008857192169068589
Epoch: 60000   Error: 0.008061225259450217
Epoch: 70000   Error: 0.007445742506199956
Epoch: 80000   Error: 0.006951582949193435
Epoch: 90000   Error: 0.006543577682919596
Epoch: 100000   Error: 0.006199340225340663

Testing:
Desired Output: [0]
Predicted Output: [0.01004773]
Desired Output: [1]
Predicted Output: [0.99334685]
Desired Output: [1]
Predicted Output: [0.99405099]
Desired Output: [0]
Predicted Output: [0.00214735]


In [ ]:
Generate 500 vectors containing 4 components each. The value of each
component should be a random number between -1 and 1. These will be
your input vectors. The corresponding output for each vector should be
the sin() of a combination of the components. Specifically, for inputs:
[x1 x2 x3 x4]
the (single component) output should be:
sin(x1-x2+x3-x4)

In [18]:
vectors = []
sin_output = []
for i in range(0, 500):
    vector = list(np.random.uniform(-1.0, 1.0, 4))
    vector = [float(vector[0]), float(vector[1]), float(vector[2]), float(vector[3])]
    vectors.append(vector)

vectors = np.array(vectors)

for i in range(0, 500):
    for j in range(0,1):
        sin_output.append([np.sin(vectors[i][j]-vectors[i][j+1]+vectors[i][j+2]-vectors[i][j+3])])

sin_output = np.array(sin_output)

print('Vectors : ',vectors)
print()
print('No. of Vectors : ',len(vectors))
print()

Vectors :  [[ 0.80391536 -0.17693245 -0.04653189  0.44280551]
 [-0.75560637  0.0061301   0.62629533  0.35468372]
 [-0.35669855  0.42133079  0.8688792   0.78955248]
 ...
 [-0.03621634 -0.84375492  0.82021168  0.11845148]
 [ 0.04997233 -0.46609622  0.79998577 -0.97217286]
 [-0.80599773 -0.87985015 -0.51815531 -0.00630158]]

No. of Vectors :  500



In [6]:
print('Sin_output',sin_output)

Sin_output [[ 5.55152784e-02]
 [-8.81696982e-01]
 [ 9.99507841e-01]
 [-9.82161545e-01]
 [-5.10941597e-01]
 [ 5.14674249e-01]
 [-8.43326586e-01]
 [ 6.95118081e-01]
 [ 5.92269351e-01]
 [-6.29596727e-02]
 [-6.24174761e-01]
 [ 7.79369434e-01]
 [-7.65349771e-01]
 [ 9.35302745e-01]
 [ 9.69542509e-01]
 [-7.28533242e-01]
 [-9.99884502e-01]
 [ 8.51614075e-02]
 [-5.38915484e-01]
 [ 6.10362608e-01]
 [-9.51132151e-01]
 [-5.16229280e-01]
 [-7.87887572e-01]
 [ 7.42108697e-01]
 [-4.33588121e-01]
 [ 6.39323089e-02]
 [-8.80868429e-01]
 [ 7.96515499e-01]
 [ 8.77838067e-01]
 [ 6.56914064e-01]
 [-8.91408571e-01]
 [-6.41369632e-01]
 [-2.50683044e-01]
 [-5.01625289e-01]
 [-7.99158648e-01]
 [-5.27976007e-01]
 [-9.54372532e-01]
 [ 1.04354803e-02]
 [ 1.99774665e-01]
 [ 8.01660302e-01]
 [-9.17066683e-01]
 [-3.94573792e-01]
 [-1.22230144e-01]
 [-8.93597524e-01]
 [ 9.72358076e-01]
 [-8.23474303e-02]
 [-9.00917000e-01]
 [-6.01928342e-01]
 [-2.26709452e-01]
 [-9.95209079e-01]
 [-9.77278163e-01]
 [-2.90021063e-01]
 

In [7]:
no_of_epochs = 500000
learning_rate = 0.005
inputs = 4
hidden = 5
outputs = 1

mlp = MLP(inputs, hidden, outputs)
mlp.randomise()

print('Pre-Training Testing:')
for i in range(len(vectors) - 10, len(vectors)):
    mlp.forward(vectors[i],tan=True)
    print('Desired Output: ' + str(sin_output[i]))
    print('Predicted Output: ' + str(mlp.o))

print()
print('After Training: ')
for i in range(0, no_of_epochs):
    error = 0
    mlp.forward(vectors[:len(vectors) - 100], tan=True)
    error = mlp.backwards(vectors[:(len(vectors) - 100)], sin_output[:len(vectors) - 100], tan=True)
    mlp.updateWeights(learning_rate)
    if (i + 1) % (no_of_epochs / 10) == 0:
        length = len(str(i))
        while length < 100:
            length += 1
        print('Epoch: ' + str(i + 1) + "   " + 'Error: ' + str(error))

print()
print('Testing: ')
for i in range(len(vectors) - 100, len(vectors)):
    mlp.forward(vectors[i], tan=True)
    print('Desired Output: ' + str(sin_output[i]))
    print('Predicted Output: ' + str(mlp.o))

Pre-Training Testing:
Desired Output: [0.95174962]
Predicted Output: [-0.59234067]
Desired Output: [0.92183257]
Predicted Output: [-0.61652474]
Desired Output: [0.34112372]
Predicted Output: [0.50004275]
Desired Output: [-0.02091992]
Predicted Output: [0.45006627]
Desired Output: [0.11672324]
Predicted Output: [0.3245332]
Desired Output: [0.88270138]
Predicted Output: [-0.37757419]
Desired Output: [0.26281467]
Predicted Output: [0.44385276]
Desired Output: [0.17682257]
Predicted Output: [-0.78165503]
Desired Output: [0.74258982]
Predicted Output: [-0.44201102]
Desired Output: [0.06814983]
Predicted Output: [0.82716567]

After Training: 
Epoch: 50000   Error: 0.07627983856088585
Epoch: 100000   Error: 0.0762804191915113
Epoch: 150000   Error: 0.07628041933058104
Epoch: 200000   Error: 0.07628041933061142
Epoch: 250000   Error: 0.07628041933061142
Epoch: 300000   Error: 0.07628041933061142
Epoch: 350000   Error: 0.07628041933061142
Epoch: 400000   Error: 0.07628041933061142
Epoch: 450000

In [8]:
import pandas as pd
vectors = []
desired_sin_output = []
for i in range(0, 500):
    vector = list(np.random.uniform(-1.0, 1.0, 4))
    vector = [float(vector[0]), float(vector[1]), float(vector[2]), float(vector[3])]
    vectors.append(vector)

vectors = np.array(vectors)

fifty_vectors_df=pd.DataFrame(vectors)
fifty_vectors_df['target']=fifty_vectors_df[0]-fifty_vectors_df[1]+fifty_vectors_df[2]-fifty_vectors_df[3]
fifty_vectors_df['desired_sin_output']=np.sin(fifty_vectors_df.target)
for sin_value in fifty_vectors_df['desired_sin_output']:
    lst1=[]
    lst1.append(sin_value)
    desired_sin_output.append(lst1)
    
desired_sin_output= np.array(desired_sin_output)

print('Vectors : ',vectors)
print()
print('No. of Vectors : ',len(vectors))
print()
print('Desired Output:', desired_sin_output)

Vectors :  [[ 0.64891922  0.70794483  0.19165988 -0.51965253]
 [-0.62701462  0.48678102 -0.52557188  0.07898178]
 [ 0.49856157 -0.54350179 -0.65099762 -0.92052863]
 ...
 [-0.79219778 -0.88674729  0.36159207 -0.95473057]
 [-0.91140182 -0.92609395 -0.06917898  0.51573889]
 [ 0.98439845 -0.54678461  0.58476045  0.59049173]]

No. of Vectors :  500

Desired Output: [[ 0.60700531]
 [-0.98913379]
 [ 0.96659483]
 [-0.99719166]
 [-0.99678733]
 [-0.54206054]
 [ 0.94271374]
 [-0.42426779]
 [ 0.79231036]
 [ 0.99972331]
 [-0.07738182]
 [ 0.61586142]
 [ 0.53240204]
 [ 0.11899111]
 [-0.41673364]
 [-0.82737773]
 [-0.96486581]
 [ 0.23299549]
 [-0.02854615]
 [-0.53843437]
 [ 0.97729839]
 [ 0.82178514]
 [ 0.09120354]
 [ 0.39274528]
 [ 0.56078333]
 [-0.62922765]
 [-0.29170923]
 [ 0.99929032]
 [ 0.52726513]
 [-0.69913498]
 [-0.99970134]
 [-0.33513993]
 [ 0.72365388]
 [ 0.98998447]
 [-0.12049866]
 [ 0.97053859]
 [ 0.9801065 ]
 [ 0.21199843]
 [-0.92329646]
 [-0.92650043]
 [ 0.67388722]
 [-0.4836189 ]
 [-0.99

In [9]:
no_of_epochs = 200000
learning_rate = 0.005
inputs = 4
hidden = 5
outputs = 1

mlp = MLP(inputs, hidden, outputs)
mlp.randomise()

print('Pre-Training Testing:')
for i in range(len(vectors) - 10, len(vectors)):
    mlp.forward(vectors[i],tan=True)
    print('Desired Output: ' + str(desired_sin_output[i]))
    print('Predicted Output: ' + str(mlp.o))

print()
print('After Training: ')
for i in range(0, no_of_epochs):
    error = 0
    mlp.forward(vectors[:len(vectors) - 100], tan=True)
    error = mlp.backwards(vectors[:(len(vectors) - 100)], desired_sin_output[:len(vectors) - 100], tan=True)
    mlp.updateWeights(learning_rate)
    if (i + 1) % (no_of_epochs / 10) == 0:
        length = len(str(i))
        while length < 100:
            length += 1
        print('Epoch: ' + str(i + 1) + "   " + 'Error: ' + str(error))

print()
print('Testing: ')
for i in range(len(vectors) - 100, len(vectors)):
    mlp.forward(vectors[i], tan=True)
    print('Desired Output: ' + str(desired_sin_output[i]))
    print('Predicted Output: ' + str(mlp.o))

Pre-Training Testing:
Desired Output: [-0.84716922]
Predicted Output: [-0.48148005]
Desired Output: [0.46180839]
Predicted Output: [0.73430878]
Desired Output: [-0.38669034]
Predicted Output: [-0.49942051]
Desired Output: [0.80535347]
Predicted Output: [-0.84849657]
Desired Output: [-0.79734836]
Predicted Output: [-0.76221814]
Desired Output: [-0.97455059]
Predicted Output: [0.00639885]
Desired Output: [-0.99035055]
Predicted Output: [0.38889517]
Desired Output: [0.98723936]
Predicted Output: [-0.87938861]
Desired Output: [-0.53982208]
Predicted Output: [-0.36459696]
Desired Output: [0.99897211]
Predicted Output: [0.90188052]

After Training: 
Epoch: 20000   Error: 0.08753098757793742
Epoch: 40000   Error: 0.08844262395414045
Epoch: 60000   Error: 0.08721349474918202
Epoch: 80000   Error: 0.08413425350418528
Epoch: 100000   Error: 0.08903240597124583
Epoch: 120000   Error: 0.08962256227803536
Epoch: 140000   Error: 0.08350173802803025
Epoch: 160000   Error: 0.08762434694802945
Epoch: 1

In [10]:
import pandas as pd
training_data = []
desired_output = []
desired_output_numbers = []

df = pd.read_csv("letter-recognition.data", header = None)
df = df.rename(columns = {0:'Letters'})
#with open('letter_recognition_data.csv', 'r') as f:
#   for line in f:
 #       training_data.append(line.rstrip('\n').split(','))
  #      desired_output.append(line.rstrip('\n').split(',')[0])

#for i in range(len(desired_output)):
 #   desired_output_numbers.append(ord(str(desired_output[i]).lower()) - 96)

In [11]:
df

Letters  1   2  3  4  5   6   7  8  9  10  11  12  13  14  15  16
0           T  2   8  3  5  1   8  13  0  6   6  10   8   0   8   0   8
1           I  5  12  3  7  2  10   5  5  4  13   3   9   2   8   4  10
2           D  4  11  6  8  6  10   6  2  6  10   3   7   3   7   3   9
3           N  7  11  6  6  3   5   9  4  6   4   4  10   6  10   2   8
4           G  2   1  3  1  1   8   6  6  6   6   5   9   1   7   5  10
...       ... ..  .. .. .. ..  ..  .. .. ..  ..  ..  ..  ..  ..  ..  ..
19995       D  2   2  3  3  2   7   7  7  6   6   6   4   2   8   3   7
19996       C  7  10  8  8  4   4   8  6  9  12   9  13   2   9   3   7
19997       T  6   9  6  7  5   6  11  3  7  11   9   5   2  12   2   4
19998       S  2   3  4  2  1   8   7  2  6  10   6   8   1   9   5   8
19999       A  4   9  6  6  2   9   5  3  1   8   1   8   2   7   2   8

[20000 rows x 17 columns]

In [12]:
desired_output = df.pop('Letters').values

In [13]:
desired_output

array(['T', 'I', 'D', ..., 'T', 'S', 'A'], dtype=object)

In [14]:
training_data = df.values

In [15]:
training_data

array([[ 2,  8,  3, ...,  8,  0,  8],
       [ 5, 12,  3, ...,  8,  4, 10],
       [ 4, 11,  6, ...,  7,  3,  9],
       ...,
       [ 6,  9,  6, ..., 12,  2,  4],
       [ 2,  3,  4, ...,  9,  5,  8],
       [ 4,  9,  6, ...,  7,  2,  8]], dtype=int64)

In [16]:
len(df)

20000

In [17]:
no_of_epochs = 1000
learning_rate = 0.05
inputs = 16
hidden = 10
outputs = 26
print()

print('Pre-Training Testing:')
for i in range(len(training_data)):
    mlp.forward(training_data[i])
    print('Desired Output: ' + str(desired_output[i]))
    print('Predicted Output: ' + str(mlp.o))

print()
print('After Training: ')
for i in range(0, no_of_epochs):
    error = 0
    mlp.forward(training_data[:len(training_data) - 10], tan=True)
    error = mlp.backwards(training_data[:(len(training_data) - 10)], sin_output[:len(training_data) - 10], tan=True)
    mlp.updateWeights(learning_rate)
    if (i + 1) % (no_of_epochs / 10) == 0:
        length = len(str(i))
        while length < 10:
            length += 1
        print('Epoch: ' + str(i + 1) + "   " + 'Error: ' + str(error))

print()
print('Testing: ')
for i in range(len(training_data) - 10, len(training_data)):
    mlp.forward(training_data[i], tan=True)
    print('Desired Output: ' + str(desired_output[i]))
    print('Predicted Output: ' + str(mlp.o))


Pre-Training Testing:


ValueError: shapes (16,) and (4,5) not aligned: 16 (dim 0) != 4 (dim 0)

In [20]:
# Import necessary libraries
import numpy as np
import urllib

data = pd.read_csv("letter-recognition.data", header = None)
data = data.rename(columns = {0:'Letters'})
y = data.pop('Letters').values
X = data.values

# Split the data into a training set and a testing set
n_samples = len(X)
n_train = int(0.8 * n_samples)
X_train = X[:n_train,:]
y_train = y[:n_train]
X_test = X[n_train:,:]
y_test = y[n_train:]

# Normalize the input features
X_train = X_train / 16.0
X_test = X_test / 16.0

# Define the architecture of the MLP
n_inputs = 16
n_hidden = 10
n_outputs = 26

# Initialize the weights and biases
W1 = np.random.uniform(size=(n_inputs, n_hidden))
b1 = np.zeros(n_hidden)
W2 = np.random.uniform(size=(n_hidden, n_outputs))
b2 = np.zeros(n_outputs)

# Define the activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Define the forward propagation function
def forward_prop(X, W1, b1, W2, b2):
    Z1 = X.dot(W1) + b1
    A1 = sigmoid(Z1)
    Z2 = A1.dot(W2) + b2
    A2 = sigmoid(Z2)
    return A2

# Define the backpropagation function
def backprop(X, y, A2, W1, b1, W2, b2):
    m = len(y)
    dZ2 = A2 - y
    dW2 = 1/m * np.dot(A1.T, dZ2)
    db2 = 1/m * np.sum(dZ2, axis=0)
    dZ1 = np.dot(dZ2, W2.T) * A1 * (1 - A1)
    dW1 = 1/m * np.dot(X.T, dZ1)
    db1 = 1/m * np.sum(dZ1, axis=0)
    return dW1, db1, dW2, db2

# Define the update function
def update(W1, b1, W2, b2, dW1, db1, dW2, db2, learning_rate):
    W1 -= learning_rate * dW1
    b1 -= learning_rate * db1
    b2 -= learning_rate * db2
    W2 -= learning_rate * dW2

In [21]:
# Use the trained MLP to make predictions on the testing set
y_pred = forward_prop(X_test, W1, b1, W2, b2)

# Evaluate the classification accuracy on the testing set
accuracy = np.mean(np.argmax(y_pred, axis=1) == y_test)
print('Classification accuracy on pre training dataset:', accuracy)

Classification accuracy on pre training dataset: 0.0


In [22]:
# Set the number of epochs and the learning rate
n_epochs = 1000
learning_rate = 0.1

# Train the MLP for 1000 epochs
for epoch in range(n_epochs):
    # Forward propagate the input
    A2 = forward_prop(X_train, W1, b1, W2, b2)

    # Backpropagate the error
    dW1, db1, dW2, db2 = backprop(X_train, y_train, A2, W1, b1, W2, b2)

    # Update the weights and biases
    W1, b1, W2, b2 = update(W1, b1, W2, b2, dW1, db1, dW2, db2, learning_rate)

# Use the trained MLP to make predictions on the testing set
y_pred = forward_prop(X_test, W1, b1, W2, b2)

# Evaluate the classification accuracy on the testing set
accuracy = np.mean(np.argmax(y_pred, axis=1) == y_test)
print('Classification accuracy on testing set:', accuracy)

ValueError: operands could not be broadcast together with shapes (16000,26) (16000,) 